    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author angel
 */
public class AvengerPagina extends javax.swing.JFrame {

    
     private int boletosDisponibles = 30; // Número de asientos disponibles
    private int boletosSeleccionados = 0; // Número de asientos seleccionados
      private ArrayList<Integer> asientosSeleccionados = new ArrayList<>();
    
  
    /**
     * Creates new form KimetsuPagina
     */
    public AvengerPagina() {
  
        initComponents();
        this.setLocationRelativeTo(null);
        
        for (int i = 1; i <= boletosDisponibles; i++) {
            JButton botonAsiento = new JButton("Asiento " + i);
            botonAsiento.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                     if (boletosSeleccionados < boletosDisponibles) {
                        JButton boton = (JButton) e.getSource();
                        boton.setEnabled(false);
                        int numeroAsiento = Integer.parseInt(boton.getText().replace("Asiento ", ""));
                        asientosSeleccionados.add(numeroAsiento); // Agregar el número de asiento a la colección
                        boletosSeleccionados++;
                        actualizarInfo();
                    } else {
                        JOptionPane.showMessageDialog(AvengerPagina.this, "Ya ha seleccionado todos los asientos permitidos.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            });
            panelAsientos.add(botonAsiento);
        }
                   
        
         spinnerCantidad.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int cantidad = (int) spinnerCantidad.getValue();
                boletosDisponibles = cantidad;
                actualizarInfo();
            }
        });
        
    }
    
     public void abrirNuevoJFrame() {
        // Crear una instancia del nuevo JFrame y pasar los datos de los asientos
        KimetsuPagar kimetsuPagar = new KimetsuPagar(asientosSeleccionados, boletosSeleccionados);
        dispose();
        kimetsuPagar.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        guardarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        panelAsientos = new javax.swing.JPanel();
        labelInfo = new javax.swing.JLabel();
        PagarBtn = new javax.swing.JButton();
        Pantalla = new javax.swing.JLabel();
        fondillo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarBtn.setBackground(new java.awt.Color(255, 153, 153));
        guardarBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        guardarBtn.setForeground(new java.awt.Color(0, 0, 0));
        guardarBtn.setText("Guardar");
        guardarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBtnMouseClicked(evt);
            }
        });
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("x $40.00 pesos el boleto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 280, 40));

        text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 204, 204));
        text.setText("¡Escoja cuantos boletos desea comprar!");
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finityChi.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 180));

        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("a su familia, este busca venganza. ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 50));

        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Despues de que nuestro protagonista perdiera ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, 50));

        spinnerCantidad.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        spinnerCantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spinnerCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spinnerCantidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinnerCantidadPropertyChange(evt);
            }
        });
        jPanel1.add(spinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 80, 30));

        jButton1.setBackground(new java.awt.Color(202, 151, 166));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 30));

        panelAsientos.setBackground(new java.awt.Color(102, 102, 102));
        panelAsientos.setLayout(new java.awt.GridLayout(6, 0));
        jPanel1.add(panelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 520, 280));
        panelAsientos.getAccessibleContext().setAccessibleParent(jLabel1);

        labelInfo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(255, 204, 255));
        jPanel1.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 270, 40));

        PagarBtn.setBackground(new java.awt.Color(255, 153, 153));
        PagarBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        PagarBtn.setForeground(new java.awt.Color(0, 0, 0));
        PagarBtn.setText("Pagar");
        PagarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PagarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PagarBtnMouseClicked(evt);
            }
        });
        PagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PagarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 130, 30));

        Pantalla.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        Pantalla.setForeground(new java.awt.Color(153, 0, 0));
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pantalla.setText("PANTALLA");
        jPanel1.add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 430, 20));

        fondillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login.png"))); // NOI18N
        jPanel1.add(fondillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Inicio principal = new Inicio();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void guardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseClicked
        
    }//GEN-LAST:event_guardarBtnMouseClicked

    private void spinnerCantidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinnerCantidadPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerCantidadPropertyChange

    private void PagarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagarBtnMouseClicked
          AvengerPagar principal = new AvengerPagar(asientosSeleccionados, boletosSeleccionados);
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_PagarBtnMouseClicked

    private void PagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagarBtnActionPerformed

     private void actualizarInfo() {
              labelInfo.setText("Asientos seleccionados: " + boletosSeleccionados + "/" + boletosDisponibles);
            }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvengerPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvengerPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvengerPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvengerPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvengerPagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PagarBtn;
    private javax.swing.JLabel Pantalla;
    private javax.swing.JLabel fondillo;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JPanel panelAsientos;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
