/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

/**
 *
 * @author angel
 */
public class DulceriaPagar extends javax.swing.JFrame {
    private int spinnerValor;
    private int valorSpinner;
    private int mufinSpinner;

    /**
     * Creates new form DulceriaPagar
     */
    public DulceriaPagar(int spinnerValor, int valorSpinner, int mufinSpinner) {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
        this.spinnerValor = spinnerValor;
        this.valorSpinner = valorSpinner;
        this.mufinSpinner = mufinSpinner;
        
        
        
        
        
        // palomitas
        int valor = 70;
        int palomitas = spinnerValor * valor;
        
        if (spinnerValor == 0){
            
        }else{
            lblP.setText(Integer.toString(spinnerValor)+ "  x  $70 es igual a $"+ palomitas);
        }
        
        
        // refresco
        int precio = 60;
        int refresco = valorSpinner * precio;
        
        if (valorSpinner == 0){
            
        }else{
            lblR.setText(Integer.toString(valorSpinner)+ "  x  $60 es igual a $"+ refresco);
        }
        
        // mufin
        int mufinPrecio = 50;
        int mufin = mufinSpinner * mufinPrecio;
        
        if (mufinSpinner == 0){
            
        }else{
             lblM.setText(Integer.toString(mufinSpinner)+ "  x  $50 es igual a $" + mufin);
        }
        
      
        
        //total
        
        lblT.setText("el valor total a pagar es de:   $" + Integer.toString( palomitas + refresco + mufin));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblR = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ticket = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REFRESCOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 300, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 300, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PALOMITAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 300, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MUFIN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 300, 20));

        lblP.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblP.setForeground(new java.awt.Color(0, 0, 0));
        lblP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 300, 30));

        lblR.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblR.setForeground(new java.awt.Color(0, 0, 0));
        lblR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 300, 30));

        lblM.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblM.setForeground(new java.awt.Color(0, 0, 0));
        lblM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 300, 30));

        lblT.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblT.setForeground(new java.awt.Color(0, 0, 0));
        lblT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 300, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 110, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 110, 30));

        ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ticket.png"))); // NOI18N
        jPanel1.add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 320, 430));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DulceriaComprar principal = new DulceriaComprar ();
        dispose ();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inicio principal = new Inicio ();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DulceriaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DulceriaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DulceriaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DulceriaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel ticket;
    // End of variables declaration//GEN-END:variables
}
