/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;


public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Publi1 = new javax.swing.JLabel();
        Publi2 = new javax.swing.JLabel();
        Publi3 = new javax.swing.JLabel();
        Publi4 = new javax.swing.JLabel();
        Publi5 = new javax.swing.JLabel();
        logoInicio = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BOTONCITO.png"))); // NOI18N
        jButton1.setText("Dulceria");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BOTONCITOpress.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 160, 30));

        Publi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kimetsu1.png"))); // NOI18N
        Publi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publi1MouseClicked(evt);
            }
        });
        jPanel1.add(Publi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 220, 320));
        Publi1.getAccessibleContext().setAccessibleName("");

        Publi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/elGato1.png"))); // NOI18N
        Publi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publi2MouseClicked(evt);
            }
        });
        jPanel1.add(Publi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 220, 320));

        Publi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/avatar1.png"))); // NOI18N
        Publi3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publi3MouseClicked(evt);
            }
        });
        jPanel1.add(Publi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 220, 320));

        Publi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ballena.png"))); // NOI18N
        Publi4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publi4MouseClicked(evt);
            }
        });
        jPanel1.add(Publi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, 220, 320));

        Publi5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/infinity.png"))); // NOI18N
        Publi5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publi5MouseClicked(evt);
            }
        });
        jPanel1.add(Publi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 100, 220, 320));

        logoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        jPanel1.add(logoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, 50));
        minimizar.getAccessibleContext().setAccessibleName("");

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Delete_32px.png"))); // NOI18N
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 50));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NEXT.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 50, 30));

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BACK.png"))); // NOI18N
        btnNext.setToolTipText("");
        btnNext.setBorder(null);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 50, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        AnimationClass aacc = new AnimationClass();
        aacc.jLabelXRight(-650, 50, 25, 5, Publi1);
        
        AnimationClass aac = new AnimationClass();
        aac.jLabelXRight(-300, 400, 25, 5, Publi2);
        
        AnimationClass aaac = new AnimationClass();
        aaac.jLabelXRight(50, 750, 25, 5, Publi3);
        
        AnimationClass aaaac = new AnimationClass();
        aaaac.jLabelXRight(400, 1100, 25, 5, Publi4);
        
        AnimationClass aaaaac = new AnimationClass();
        aaaaac.jLabelXRight(750, 1450, 25, 5, Publi5);
        
        
    }//GEN-LAST:event_btnBackMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
         AnimationClass ac = new AnimationClass();
        ac.jLabelXLeft(50, -650, 25, 5, Publi1);
        
        AnimationClass acc = new AnimationClass();
        acc.jLabelXLeft(400, -300, 25, 5, Publi2);
        
        AnimationClass accc = new AnimationClass();
        accc.jLabelXLeft(750, 50, 25, 5, Publi3);
        
        AnimationClass acccc = new AnimationClass();
        acccc.jLabelXLeft(1100, 400, 25, 5, Publi4);
        
        AnimationClass accccc = new AnimationClass();
        accccc.jLabelXLeft(1450, 750, 25, 5, Publi5);
        
        
    }//GEN-LAST:event_btnNextMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        
        try{
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?","EXIT",dialogButton);
        if (result == 0){
            System.exit(0);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_CerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(yFrame.Inicio.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Dulceria principal = new Dulceria();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void Publi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publi1MouseClicked
        KimetsuPagina principal = new KimetsuPagina();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Publi1MouseClicked

    private void Publi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publi2MouseClicked
        GatoPagina principal = new GatoPagina();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Publi2MouseClicked

    private void Publi3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publi3MouseClicked
       AvatarPagina principal = new AvatarPagina();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Publi3MouseClicked

    private void Publi4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publi4MouseClicked
        BallenaPagina principal = new BallenaPagina();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Publi4MouseClicked

    private void Publi5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publi5MouseClicked
       AvengerPagina principal = new AvengerPagina();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Publi5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Publi1;
    private javax.swing.JLabel Publi2;
    private javax.swing.JLabel Publi3;
    private javax.swing.JLabel Publi4;
    private javax.swing.JLabel Publi5;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables
}
